/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entity.Randevu;
import Model.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nurcan
 */
public class Randevularım extends javax.swing.JFrame {

    /**
     * Creates new form randevularım
     */
    public Randevularım() {
        initComponents();
        tabloyudoldur();
    }

     DefaultTableModel model;
    public void tabloyudoldur() 
    {
          model=(DefaultTableModel)tblrandevular.getModel(); 
          model.setRowCount(0); 
        try {
            ArrayList<Randevu> randevular=getRandevu();
            for(Randevu rnd: randevular )
            {
                Object[] row={rnd.getDoktoradi(),rnd.getPoliklinik(), rnd.getRandevusaati()};
                model.addRow(row);
                        }
                    } catch (SQLException ex) {
            
        }
    }
    
    public ArrayList<Randevu> getRandevu() throws SQLException{
    Connection connection=null;
    DBConnection db=new DBConnection();
    Statement statement =null;
    ResultSet resultSet;
    ArrayList<Randevu> duyurular =null;
    
    try{
        connection=db.connect();
        statement = connection.createStatement();
        resultSet=statement.executeQuery("select * from randevularım");
        duyurular=new ArrayList<Randevu>();
        
       while(resultSet.next())
     {
          duyurular.add(new Randevu  
                ( resultSet.getString("doktoradi"), 
                  resultSet.getString("poliklinik"),
                  resultSet.getString("randevusaati")
                ));
     }
        
        
    }catch(SQLException exception)
     {
        
     }finally
    {
        statement.close();
        connection.close();
    }
    return duyurular;
            
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrandevular = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblrandevular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblrandevular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblrandevular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "doktoradi", "poliklinik", "randevusaati"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblrandevular);
        if (tblrandevular.getColumnModel().getColumnCount() > 0) {
            tblrandevular.getColumnModel().getColumn(0).setResizable(false);
            tblrandevular.getColumnModel().getColumn(1).setResizable(false);
            tblrandevular.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblrandevular;
    // End of variables declaration//GEN-END:variables
}
